draw_self()
draw_text(room_width/2, room_height/2, current_state)
draw_text(room_width/2, room_height/2+40, jumpy)
draw_text(room_width/2, room_height/2+80, place_meeting(x, y + 1, obj_platform_test))
draw_text(room_width/2, room_height/2 + 120, image_index)
draw_text(room_width/2, room_height/2 + 160, fall)
draw_text(room_width/2, room_height/2 + 200, plsfall)